---
title: "MAFtools"
output: html_document
date: "2022-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(maftools)
```



```{r}
endometrial_maf <- tcgaLoad(study= "UCEC")
```

```{r}
#Shows sample summry.
getSampleSummary(endometrial_maf)
```


```{r}
#Shows gene summary.
getGeneSummary(endometrial_maf)
```

```{r}
#shows clinical data associated with samples
getClinicalData(endometrial_maf)
```

```{r}
#Shows all fields in MAF
getFields(endometrial_maf)
```

```{r}
#Writes maf summary to an output file with basename laml.
write.mafSummary(maf = endometrial_maf, basename = 'endometrial_maf')
```

```{r}
plotmafSummary(maf = endometrial_maf, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```
```{r}
oncoplot(maf = endometrial_maf, top = 10)
```
```{r}
laml.titv = titv(maf = endometrial_maf, plot = FALSE, useSyn = TRUE)
#plot titv summary
plotTiTv(res = laml.titv)

```
#I think this is a great thing to add a field in to make it interactive 
```{r}
  lollipopPlot(
  maf = endometrial_maf,
  gene = 'PTEN',
  AACol = 'HGVSp_Short',
  showMutationRate = TRUE
)
```
```{r}
rainfallPlot(maf = endometrial_maf, detectChangePoints = TRUE, pointSize = 0.4)
```
```{r}
somaticInteractions(maf = endometrial_maf, top = 25, pvalue = c(0.05, 0.1))
```
```{r}
laml.sig = oncodrive(maf = endometrial_maf, AACol = 'HGVSp_Short', minMut = 5, pvalMethod = 'zscore')
```

```{r}
plotOncodrive(res = laml.sig, fdrCutOff = 0.1, useFraction = TRUE, labelSize = 0.5)
```

